use_frameworks!

target 'UIViewToolkit_Example' do
  pod 'UIViewToolkit', :path => '../'

  target 'UIViewToolkit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
